#! /bin/bash

command -v git >/dev/null 2>&1 || { echo >&2 "git is not installed.  Aborting."; exit 1; }

get_last_tag()
{
    echo `git for-each-ref --format='%(*committerdate:raw)%(committerdate:raw) %(refname:short)' refs/tags | sort -n -r | awk '{ print $3; }' | head -n 1`

}

increment_patch()
{
    versions=($(get_last_tag | tr "." "\n"))
    major=$((versions[0]))
    minor=$((versions[1]))
    patch=$((++versions[2]))

    git tag "${major}.${minor}.${patch}"
}

# Print previous tag
echo "Previous tag: $(get_last_tag)"

# Increment patch by default
increment_patch

# Print tagged version
echo "Latest tag: $(get_last_tag)"

# Push last tag to upstream branch
git push upstream $(get_last_tag)
